import { createHash } from "node:crypto";
import {
  access,
  lstat,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  symlink,
  unlink,
  writeFile,
} from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import type { MountConfig } from "./MountConfig.js";
import { codexStartupWorker } from "./codexStartupWorker.js";

export interface CodexStartupOptions {
  /** Project-owned selection generated by sandcastle init. */
  readonly selectionFile: string;
  readonly cwd?: string;
}

/** Settings consumed by codex() for every invocation, including resumes. */
export interface CodexStartupCheck {
  readonly home: string;
  readonly snapshot: string;
  readonly timeoutMs: number;
}

export interface CodexStartupPreparation {
  readonly mounts: readonly MountConfig[];
  readonly env: Readonly<Record<string, string>>;
  readonly startupCheck: CodexStartupCheck;
}

const exists = async (path: string) =>
  access(path).then(
    () => true,
    () => false,
  );
const merge = (base: any, extra: any): any => {
  const result = { ...base };
  for (const [key, value] of Object.entries(extra))
    result[key] =
      value && typeof value === "object" && !Array.isArray(value)
        ? merge(result[key] ?? {}, value)
        : value;
  return result;
};
const effectiveConfig = (reading: any) =>
  (reading.layers ?? [])
    .filter((layer: any) => !layer.disabledReason)
    .reverse()
    .reduce((config: any, layer: any) => merge(config, layer.config), {});
// TOML inline values preserve the semantics of the effective config, including hooks.state hashes and intentional disables.
const toml = (value: any): string => {
  if (
    typeof value === "string" ||
    typeof value === "boolean" ||
    typeof value === "number"
  )
    return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(toml).join(", ")}]`;
  if (value && typeof value === "object")
    return `{ ${Object.entries(value)
      .filter(([, item]) => item !== null && item !== undefined)
      .map(([key, item]) => `${JSON.stringify(key)} = ${toml(item)}`)
      .join(", ")} }`;
  throw new Error("Unsupported Codex config value");
};
const save = async (path: string, content: string) => {
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, content, { mode: 0o600 });
  await rename(temporary, path);
};

/**
 * Register the selected host capabilities in a private container home and freeze
 * their files and trust definitions. codex() exercises them before releasing each task.
 */
export async function prepareCodexStartup(
  options: CodexStartupOptions,
): Promise<CodexStartupPreparation> {
  const cwd = resolve(options.cwd ?? process.cwd());
  const selectionPath = resolve(cwd, options.selectionFile);
  const selection = JSON.parse(await readFile(selectionPath, "utf8"));
  if (
    selection.version !== 1 ||
    !Array.isArray(selection.alwaysSkills) ||
    !selection.alwaysSkills.length ||
    selection.alwaysSkills.some(
      (name: unknown) => typeof name !== "string" || !name,
    )
  )
    throw new Error(
      "Mandatory startup selection requires version 1 and alwaysSkills",
    );
  if (
    selection.disabledHooks &&
    (typeof selection.disabledHooks !== "object" ||
      Array.isArray(selection.disabledHooks))
  )
    throw new Error(
      "Startup disabledHooks must map hook keys to disable reasons",
    );
  const timeoutMs = selection.timeoutMs ?? 120_000;
  if (
    !Number.isSafeInteger(timeoutMs) ||
    timeoutMs < 1000 ||
    timeoutMs > 600_000
  )
    throw new Error("Startup timeoutMs must be between 1000 and 600000");
  for (const key of ["plugins", "skills"])
    if (
      selection[key] !== "host" &&
      (!Array.isArray(selection[key]) ||
        selection[key].some(
          (name: unknown) => typeof name !== "string" || !name,
        ))
    )
      throw new Error(`Startup ${key} must be 'host' or a list of exact names`);
  const hostHome = resolve(process.env.CODEX_HOME ?? join(homedir(), ".codex"));
  const home = join(dirname(selectionPath), "startup");
  const sandboxHome = "/home/agent/.codex";
  const relocate = (path: string) => {
    for (const [source, target] of [
      [home, sandboxHome],
      [join(hostHome, "plugins/cache"), join(sandboxHome, "plugins/cache")],
    ] as const)
      if (path.startsWith(source + "/"))
        return target + path.slice(source.length);
    return path;
  };
  if (home === hostHome)
    throw new Error(
      "Startup storage must be separate from the host Codex home",
    );
  const host = await codexStartupWorker({
    mode: "inspect",
    cwd,
    home: hostHome,
    timeoutMs,
  });
  const select = (items: any[], names: string[] | "host", key: string) => {
    if (names === "host") return items;
    return names.map((name) => {
      const found = items.find((item) => item[key] === name);
      if (!found)
        throw new Error(`Selected ${key} is missing on the host: ${name}`);
      return found;
    });
  };
  const plugins = select(host.plugins, selection.plugins, "id");
  const skills = select(host.skills, selection.skills, "name").filter(
    (skill: any) =>
      !skill.pluginId ||
      plugins.some((plugin: any) => plugin.id === skill.pluginId),
  );
  const always = selection.alwaysSkills.map((name: string) => {
    const matches = skills.filter(
      (skill: any) =>
        skill.name === name || skill.name.split(":").at(-1) === name,
    );
    if (
      matches.length !== 1 ||
      !matches[0].enabled ||
      (matches[0].pluginId &&
        !plugins.some(
          (plugin: any) => plugin.id === matches[0].pluginId && plugin.enabled,
        ))
    )
      throw new Error(
        `Required every-session skill is missing, ambiguous, or intentionally disabled: ${name}. Preserve the disable and resolve the startup selection before task work.`,
      );
    return matches[0];
  });
  const instructions =
    "Load and apply these instructions in every agent session. Activate the other available skills when their descriptions match the task.\n\n" +
    (
      await Promise.all(
        always.map(
          async (skill: any) =>
            `# Explicit skill: $${skill.name}\n\n${await readFile(skill.path, "utf8")}`,
        ),
      )
    ).join("\n\n");
  await mkdir(home, { recursive: true, mode: 0o700 });
  let previousStates = {};
  if (await exists(join(home, "config.toml"))) {
    const previous = await codexStartupWorker({
      mode: "inspect",
      cwd,
      home,
      timeoutMs,
    });
    previousStates = effectiveConfig(previous.config).hooks?.state ?? {};
  }
  const config = effectiveConfig(host.config);
  config.hooks ??= {};
  const hostHookStates = config.hooks.state ?? {};
  config.hooks.state = { ...hostHookStates, ...previousStates };
  config.plugins ??= {};
  for (const plugin of host.plugins)
    config.plugins[plugin.id] = {
      ...(config.plugins[plugin.id] ?? {}),
      enabled:
        plugins.some((selected: any) => selected.id === plugin.id) &&
        plugin.enabled,
    };
  config.skills ??= {};
  const disabledSkills = host.skills.filter(
    (skill: any) => !skills.includes(skill) || !skill.enabled,
  );
  const skillStates = new Map<string, any>(
    (config.skills.config ?? []).map((entry: any) => [entry.path, entry]),
  );
  for (const skill of disabledSkills)
    skillStates.set(skill.path, {
      ...(skillStates.get(skill.path) ?? {}),
      path: skill.path,
      enabled: false,
    });
  config.skills.config = [...skillStates.values()];
  // The private home needs the same plugin cache and marketplace discovery paths.
  const mounts: MountConfig[] = [];
  const mount = (source: string, target = source) => {
    if (mounts.some((entry) => target.startsWith(entry.sandboxPath + "/")))
      return;
    for (let index = mounts.length - 1; index >= 0; index--)
      if (mounts[index]!.sandboxPath.startsWith(target + "/"))
        mounts.splice(index, 1);
    if (!mounts.some((entry) => entry.sandboxPath === target))
      mounts.push({ hostPath: source, sandboxPath: target, readonly: true });
  };
  const link = async (source: string, target: string) => {
    await mkdir(dirname(target), { recursive: true, mode: 0o700 });
    if (!(await exists(target))) await symlink(source, target, "dir");
    mount(source, target.replace(home + "/", sandboxHome + "/"));
    mount(source);
  };
  for (const name of ["plugins/cache"])
    if (await exists(join(hostHome, name)))
      await link(join(hostHome, name), join(home, name));
  for (const name of ["marketplaces", "bundled-marketplaces"])
    if (await exists(join(hostHome, ".tmp", name)))
      await link(join(hostHome, ".tmp", name), join(home, ".tmp", name));
  for (const plugin of plugins)
    if (plugin.marketplacePath)
      mount(dirname(dirname(dirname(plugin.marketplacePath))));
  const roots = new Map<string, string>();
  const sandboxSkills = new Map<string, string>();
  const pluginRoots = new Map<string, string>();
  const selectedSkills = join(home, "selected-skills");
  await rm(selectedSkills, { recursive: true, force: true });
  await mkdir(selectedSkills, { recursive: true, mode: 0o700 });
  const systemSkills = join(hostHome, "skills/.system");
  if (await exists(systemSkills)) {
    await symlink(systemSkills, join(selectedSkills, ".system"), "dir");
    mount(systemSkills);
    roots.set(systemSkills, await host.fingerprint(systemSkills));
  }
  for (const skill of skills) {
    let root = dirname(skill.path);
    if (skill.pluginId) {
      let search = root;
      while (true) {
        if (
          (await exists(join(search, ".codex-plugin/plugin.json"))) ||
          (await exists(join(search, ".claude-plugin/plugin.json"))) ||
          (await exists(join(search, "plugin.json")))
        ) {
          root = search;
          break;
        }
        if (dirname(search) === search)
          throw new Error(`Cannot locate plugin source for ${skill.name}`);
        search = dirname(search);
      }
      pluginRoots.set(skill.pluginId, root);
      if (relocate(skill.path) !== skill.path)
        sandboxSkills.set(skill.path, relocate(skill.path));
    } else {
      const name = createHash("sha256").update(root).digest("hex");
      if (!(await exists(join(selectedSkills, name))))
        await symlink(root, join(selectedSkills, name), "dir");
      const projectRelative = relative(cwd, root);
      if (
        projectRelative &&
        !projectRelative.startsWith("..") &&
        !projectRelative.startsWith("/")
      ) {
        const target = join("/home/agent/workspace", projectRelative);
        sandboxSkills.set(skill.path, join(target, relative(root, skill.path)));
        roots.set(target, await host.fingerprint(root));
        mount(root, target);
      }
    }
    const sha256 = roots.get(root) ?? (await host.fingerprint(root));
    roots.set(root, sha256);
    if (relocate(root) !== root) roots.set(relocate(root), sha256);
    mount(root);
  }
  const skillLink = join(home, "skills");
  if (await exists(skillLink)) {
    if (!(await lstat(skillLink)).isSymbolicLink())
      throw new Error(
        `Generated skill selection conflicts with existing storage: ${skillLink}`,
      );
    await unlink(skillLink);
  }
  await symlink(selectedSkills, skillLink, "dir");
  mount(selectedSkills, join(sandboxHome, "skills"));
  for (const skill of disabledSkills) {
    const path = sandboxSkills.get(skill.path);
    if (path) skillStates.set(path, { path, enabled: false });
  }
  config.skills.config = [...skillStates.values()];
  if (await exists(join(hostHome, "hooks"))) {
    const source = join(hostHome, "hooks");
    await link(source, join(home, "hooks"));
    roots.set(source, await host.fingerprint(source));
  }
  for (const plugin of plugins) {
    if (!pluginRoots.has(plugin.id)) {
      const cache = join(
        hostHome,
        "plugins/cache",
        plugin.id.split("@").at(-1),
        plugin.name,
      );
      if (await exists(cache)) {
        const versions = await readdir(cache);
        const matching = versions.filter(
          (version) =>
            version === plugin.localVersion ||
            version.startsWith(`${plugin.localVersion}+`),
        );
        const version =
          matching.length === 1
            ? matching[0]
            : versions.length === 1
              ? versions[0]
              : undefined;
        if (version) {
          const root = join(cache, version);
          pluginRoots.set(plugin.id, root);
          const sha256 = await host.fingerprint(root);
          roots.set(root, sha256);
          if (relocate(root) !== root) roots.set(relocate(root), sha256);
          mount(root);
        }
      }
      if (!pluginRoots.has(plugin.id) && plugin.enabled)
        throw new Error(
          `Selected plugin has no verifiable local source: ${plugin.id}. Select supported local plugins in ${selectionPath}.`,
        );
    }
  }
  const hookDoc: any = (await exists(join(hostHome, "hooks.json")))
    ? JSON.parse(await readFile(join(hostHome, "hooks.json"), "utf8"))
    : { hooks: {} };
  hookDoc.hooks ??= {};
  for (const registration of selection.hookFiles ?? []) {
    const root = pluginRoots.get(registration.pluginId);
    const plugin = plugins.find(
      (plugin: any) => plugin.id === registration.pluginId,
    );
    if (!root || !plugin?.enabled)
      throw new Error(
        `Required hook plugin is missing or disabled: ${registration.pluginId}`,
      );
    const file = resolve(root, registration.path);
    if (!file.startsWith(root + "/"))
      throw new Error("Hook file must be inside its plugin source");
    // If Codex already discovers this file through the plugin manifest, do not register it twice.
    if (
      host.hooks.some(
        (hook: any) =>
          hook.pluginId === registration.pluginId && hook.sourcePath === file,
      )
    )
      continue;
    const document = JSON.parse(await readFile(file, "utf8"));
    for (const [event, groups] of Object.entries(document.hooks ?? {})) {
      hookDoc.hooks[event] ??= [];
      for (const group of groups as any[])
        hookDoc.hooks[event].push({
          ...group,
          hooks: group.hooks.map((hook: any) => {
            if (hook.type !== "command")
              throw new Error(
                `Cannot register unsupported required hook type: ${hook.type}`,
              );
            const quote = (text: string) =>
              "'" + text.replace(/'/g, "'\\''") + "'";
            const data =
              "/plugins/data/" +
              createHash("sha256").update(registration.pluginId).digest("hex");
            return {
              ...hook,
              command: `env PLUGIN_ROOT=${quote(root)} CLAUDE_PLUGIN_ROOT=${quote(root)} PLUGIN_DATA="$CODEX_HOME${data}" CLAUDE_PLUGIN_DATA="$CODEX_HOME${data}" sh -c ${quote(`mkdir -p "$PLUGIN_DATA" && ${hook.command}`)}`,
            };
          }),
        });
    }
  }
  const instructionPath = join(home, "instructions.md");
  const instructionHash = createHash("sha256")
    .update(instructions)
    .digest("hex");
  const startupCommands = ["SessionStart", "SubagentStart"].map((event) => {
    const commandSource = `const fs=require('node:fs');const crypto=require('node:crypto');const text=fs.readFileSync(require('node:path').join(process.env.CODEX_HOME,'instructions.md'),'utf8');if(crypto.createHash('sha256').update(text).digest('hex')!==${JSON.stringify(instructionHash)})throw Error('Startup skill instructions changed; review the new exact hook definition');console.log(JSON.stringify({hookSpecificOutput:{hookEventName:${JSON.stringify(event)},additionalContext:text}}));`;
    const command = "node -e '" + commandSource.replace(/'/g, "'\\''") + "'";
    hookDoc.hooks[event] ??= [];
    hookDoc.hooks[event].push({
      hooks: [
        {
          type: "command",
          command,
          timeout: 10,
          additionalContextLimit: 0,
          statusMessage: "Loading mandatory Sandcastle skill instructions",
        },
      ],
    });
    return command;
  });
  await save(instructionPath, instructions);
  await save(join(home, "hooks.json"), JSON.stringify(hookDoc, null, 2) + "\n");
  await save(
    join(home, "config.toml"),
    Object.entries(config)
      .map(([key, value]) => `${JSON.stringify(key)} = ${toml(value)}`)
      .join("\n") + "\n",
  );
  // Inspect the definitions Codex actually registered, then preserve approval only for identical hashes.
  let registered = await codexStartupWorker({
    mode: "inspect",
    cwd,
    home,
    timeoutMs,
  });
  for (const hook of registered.hooks) {
    const old = host.hooks.find(
      (previous: any) =>
        previous.currentHash === hook.currentHash &&
        ((previous.trustStatus === "trusted" &&
          hostHookStates[previous.key]?.trusted_hash ===
            previous.currentHash) ||
          previous.trustStatus === "managed" ||
          !previous.enabled),
    );
    if (old && (!old.enabled || hook.trustStatus !== "trusted")) {
      const approvedHash =
        old.trustStatus === "managed"
          ? old.currentHash
          : hostHookStates[old.key]?.trusted_hash;
      config.hooks.state[hook.key] = {
        ...(config.hooks.state[hook.key] ?? {}),
        ...(approvedHash !== undefined ? { trusted_hash: approvedHash } : {}),
        enabled: old.enabled,
      };
    }
  }
  if (selection.disabledHooks) {
    for (const [key, reason] of Object.entries(selection.disabledHooks)) {
      if (typeof reason !== "string" || !reason.trim())
        throw new Error(`Intentional hook disable requires a reason: ${key}`);
      const hook = registered.hooks.find((hook: any) => hook.key === key);
      if (!hook || startupCommands.includes(hook.command))
        throw new Error(
          `Cannot disable missing or mandatory startup hook: ${key}`,
        );
      config.hooks.state[key] = {
        ...(config.hooks.state[key] ?? {}),
        enabled: false,
      };
    }
  }
  // Preserve the existing exact-definition state at both registration paths.
  for (const [key, state] of Object.entries(config.hooks.state))
    if (relocate(key) !== key) config.hooks.state[relocate(key)] = state;
  await save(
    join(home, "config.toml"),
    Object.entries(config)
      .map(([key, value]) => `${JSON.stringify(key)} = ${toml(value)}`)
      .join("\n") + "\n",
  );
  registered = await codexStartupWorker({
    mode: "inspect",
    cwd,
    home,
    timeoutMs,
  });
  if (
    startupCommands.some(
      (command) =>
        registered.hooks.filter(
          (hook: any) => hook.command === command && hook.enabled,
        ).length !== 1,
    )
  )
    throw new Error(
      "Mandatory startup hook was not registered or hooks are intentionally disabled. Resolve the activation selection before task work.",
    );
  const snapshot = join(home, "snapshot.json");
  await save(
    snapshot,
    JSON.stringify(
      {
        version: 1,
        hostCwd: cwd,
        registrationHome: home,
        instructions,
        alwaysSkills: always.map((skill: any) => skill.name),
        skills: skills.map((skill: any) => ({
          name: skill.name,
          path: skill.path,
          ...(sandboxSkills.has(skill.path)
            ? { sandboxPath: sandboxSkills.get(skill.path) }
            : {}),
          enabled: skill.enabled,
        })),
        plugins: plugins.map((plugin: any) => ({
          id: plugin.id,
          enabled: plugin.enabled,
          localVersion: plugin.localVersion,
        })),
        hooks: registered.hooks.map((hook: any) => ({
          ...hook,
          key: relocate(hook.key),
          sourcePath: relocate(hook.sourcePath),
          startupContext: startupCommands.includes(hook.command),
        })),
        sources: [...roots].map(([path, sha256]) => ({ path, sha256 })),
      },
      null,
      2,
    ) + "\n",
  );
  for (const name of ["config.toml", "hooks.json", "instructions.md"])
    mount(join(home, name), join(sandboxHome, name));
  // A file mount makes the provider create/chown this parent to the agent UID;
  // plugin cache directory mounts alone leave their parent owned by root.
  const sandboxSnapshot = join(sandboxHome, "plugins/sandcastle-startup.json");
  mount(snapshot, sandboxSnapshot);
  if (await exists(join(hostHome, "auth.json")))
    mount(join(hostHome, "auth.json"), join(sandboxHome, "auth.json"));
  return {
    mounts,
    env: {
      CODEX_HOME: sandboxHome,
      XDG_CONFIG_HOME: "/home/agent/.config",
      XDG_CACHE_HOME: "/home/agent/.cache",
      XDG_STATE_HOME: "/home/agent/.local/state",
    },
    startupCheck: {
      home: sandboxHome,
      snapshot: sandboxSnapshot,
      timeoutMs,
    },
  };
}
